# =========================================================
# CONFIGURACIÓN DE BASE DE DATOS (AIVEN - MUDANZA)
# =========================================================
# Reemplazamos las variables por los datos reales de Aiven
spring.datasource.url=jdbc:mysql://tmcreation-tmcreation.a.aivencloud.com:26418/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_zdgEHaDy62xT3TfVTdK
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate - Crea las tablas automáticamente en la nueva DB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# =========================================================
# CONFIGURACIÓN DE CORREO (Forzado a SSL 465 - Ignorando Render)
# =========================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=tmcreation233@gmail.com
spring.mail.password=ngescgizoncblnmj

# Propiedades mágicas para forzar SSL en lugar de TLS (Puerto 465)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# =========================================================
# CONFIGURACIÓN GOOGLE LOGIN (Se cargarán en Render)
# =========================================================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# =========================================================
# CONFIGURACIÓN DE SERVIDOR Y COOKIES
# =========================================================
server.port=${PORT:8080}
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true