# =========================================================
# CONFIGURACIÓN DE BASE DE DATOS (AIVEN - MUDANZA)
# =========================================================
# Reemplazamos las variables por los datos reales de Aiven
spring.datasource.url=jdbc:mysql://tmcreation-tmcreation.a.aivencloud.com:26418/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_zdgEHaDy62xT3TfVTdK
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate - Crea las tablas automáticamente en la nueva DB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# =========================================================
# CONFIGURACIÓN DE CORREO (Se cargarán en Render)
# =========================================================
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

# =========================================================
# CONFIGURACIÓN GOOGLE LOGIN (Se cargarán en Render)
# =========================================================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# =========================================================
# CONFIGURACIÓN DE SERVIDOR Y COOKIES
# =========================================================
server.port=${PORT:8080}
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true